
using System.Collections.Generic;

// https://app.quicktype.io/
namespace SchemaPorter.foofoo
{

    public class RootNode
    {
        public DE De { get; set; }
    }


    public class DE
    {
        public string Direction { get; set; }
        public Date Date { get; set; }
        public Time Time { get; set; }
        public Datetime Datetime { get; set; }
        public Number Number { get; set; }
        public Support Support { get; set; }
        public Activerecord Activerecord { get; set; }



        
        public string ActionviewInstancetagBlankOption { get; set; }
        public string ButtonActivate { get; set; }
        public string ButtonAdd { get; set; }
        public string ButtonAnnotate { get; set; }
        public string ButtonApply { get; set; }
        public string ButtonArchive { get; set; }
        public string ButtonBack { get; set; }
        public string ButtonCancel { get; set; }
        public string ButtonChange { get; set; }
        public string ButtonChangePassword { get; set; }
        public string ButtonCheckAll { get; set; }
        public string ButtonClear { get; set; }
        public string ButtonClose { get; set; }
        public string ButtonCollapseAll { get; set; }
        public string ButtonConfigure { get; set; }
        public string ButtonCopy { get; set; }
        public string ButtonCopyAndFollow { get; set; }
        public string ButtonCreate { get; set; }
        public string ButtonCreateAndContinue { get; set; }
        public string ButtonDelete { get; set; }
        public string ButtonDeleteMyAccount { get; set; }
        public string ButtonDownload { get; set; }
        public string ButtonDuplicate { get; set; }
        public string ButtonEdit { get; set; }
        public string ButtonEditAssociatedWikipage { get; set; }
        public string ButtonEditSection { get; set; }
        public string ButtonExpandAll { get; set; }
        public string ButtonExport { get; set; }
        public string ButtonHide { get; set; }
        public string ButtonList { get; set; }
        public string ButtonLock { get; set; }
        public string ButtonLogTime { get; set; }
        public string ButtonLogin { get; set; }
        public string ButtonMove { get; set; }
        public string ButtonMoveAndFollow { get; set; }
        public string ButtonQuote { get; set; }
        public string ButtonRename { get; set; }
        public string ButtonReopen { get; set; }
        public string ButtonReply { get; set; }
        public string ButtonReset { get; set; }
        public string ButtonRollback { get; set; }
        public string ButtonSave { get; set; }
        public string ButtonShow { get; set; }
        public string ButtonSort { get; set; }
        public string ButtonSubmit { get; set; }
        public string ButtonTest { get; set; }
        public string ButtonUnarchive { get; set; }
        public string ButtonUncheckAll { get; set; }
        public string ButtonUnlock { get; set; }
        public string ButtonUnwatch { get; set; }
        public string ButtonUpdate { get; set; }
        public string ButtonView { get; set; }
        public string ButtonWatch { get; set; }
        public string DefaultActivityDesign { get; set; }
        public string DefaultActivityDevelopment { get; set; }
        public string DefaultDocCategoryTech { get; set; }
        public string DefaultDocCategoryUser { get; set; }
        public string DefaultIssueStatusClosed { get; set; }
        public string DefaultIssueStatusFeedback { get; set; }
        public string DefaultIssueStatusInProgress { get; set; }
        public string DefaultIssueStatusNew { get; set; }
        public string DefaultIssueStatusRejected { get; set; }
        public string DefaultIssueStatusResolved { get; set; }
        public string DefaultPriorityHigh { get; set; }
        public string DefaultPriorityImmediate { get; set; }
        public string DefaultPriorityLow { get; set; }
        public string DefaultPriorityNormal { get; set; }
        public string DefaultPriorityUrgent { get; set; }
        public string DefaultRoleDeveloper { get; set; }
        public string DefaultRoleManager { get; set; }
        public string DefaultRoleReporter { get; set; }
        public string DefaultTrackerBug { get; set; }
        public string DefaultTrackerFeature { get; set; }
        public string DefaultTrackerSupport { get; set; }
        public string DescriptionAllColumns { get; set; }
        public string DescriptionAvailableColumns { get; set; }
        public string DescriptionChooseProject { get; set; }
        public string DescriptionDateFrom { get; set; }
        public string DescriptionDateRangeInterval { get; set; }
        public string DescriptionDateRangeList { get; set; }
        public string DescriptionDateTo { get; set; }
        public string DescriptionFilter { get; set; }
        public string DescriptionIssueCategoryReassign { get; set; }
        public string DescriptionMessageContent { get; set; }
        public string DescriptionNotes { get; set; }
        public string DescriptionProjectScope { get; set; }
        public string DescriptionQuerySortCriteriaAttribute { get; set; }
        public string DescriptionQuerySortCriteriaDirection { get; set; }
        public string DescriptionSearch { get; set; }
        public string DescriptionSelectedColumns { get; set; }
        public string DescriptionUserMailNotification { get; set; }
        public string DescriptionWikiSubpagesReassign { get; set; }
        public string EnumerationActivities { get; set; }
        public string EnumerationDocCategories { get; set; }
        public string EnumerationIssuePriorities { get; set; }
        public string EnumerationSystemActivity { get; set; }
        public string ErrorAttachmentTooBig { get; set; }
        public string ErrorCanNotArchiveProject { get; set; }
        public string ErrorCanNotDeleteCustomField { get; set; }
        public string ErrorCanNotDeleteTracker { get; set; }
        public string ErrorCanNotRemoveRole { get; set; }
        public string ErrorCanNotReopenIssueOnClosedVersion { get; set; }
        public string ErrorCanTLoadDefaultData { get; set; }
        public string ErrorIssueDoneRatiosNotUpdated { get; set; }
        public string ErrorIssueNotFoundInProject { get; set; }
        public string ErrorNoDefaultIssueStatus { get; set; }
        public string ErrorNoTrackerInProject { get; set; }
        public string ErrorScmAnnotate { get; set; }
        public string ErrorScmAnnotateBigTextFile { get; set; }
        public string ErrorScmCommandFailed { get; set; }
        public string ErrorScmNotFound { get; set; }
        public string ErrorSessionExpired { get; set; }
        public string ErrorUnableDeleteIssueStatus { get; set; }
        public string ErrorUnableToConnect { get; set; }
        public string ErrorWorkflowCopySource { get; set; }
        public string ErrorWorkflowCopyTarget { get; set; }
        public string FieldAccount { get; set; }
        public string FieldActive { get; set; }
        public string FieldActivity { get; set; }
        public string FieldAdmin { get; set; }
        public string FieldAssignable { get; set; }
        public string FieldAssignedTo { get; set; }
        public string FieldAssignedToRole { get; set; }
        public string FieldAttrFirstname { get; set; }
        public string FieldAttrLastname { get; set; }
        public string FieldAttrLogin { get; set; }
        public string FieldAttrMail { get; set; }
        public string FieldAuthSource { get; set; }
        public string FieldAuthSourceLdapFilter { get; set; }
        public string FieldAuthor { get; set; }
        public string FieldBaseDn { get; set; }
        public string FieldBoardParent { get; set; }
        public string FieldCategory { get; set; }
        public string FieldColumnNames { get; set; }
        public string FieldClosedOn { get; set; }
        public string FieldComments { get; set; }
        public string FieldCommentsSorting { get; set; }
        public string FieldCommitLogsEncoding { get; set; }
        public string FieldContent { get; set; }
        public string FieldCoreFields { get; set; }
        public string FieldCreatedOn { get; set; }
        public string FieldCvsModule { get; set; }
        public string FieldCvsroot { get; set; }
        public string FieldDefaultValue { get; set; }
        public string FieldDefaultStatus { get; set; }
        public string FieldDelay { get; set; }
        public string FieldDescription { get; set; }
        public string FieldDoneRatio { get; set; }
        public string FieldDownloads { get; set; }
        public string FieldDueDate { get; set; }
        public string FieldEditable { get; set; }
        public string FieldEffectiveDate { get; set; }
        public string FieldEstimatedHours { get; set; }
        public string FieldFieldFormat { get; set; }
        public string FieldFilename { get; set; }
        public string FieldFilesize { get; set; }
        public string FieldFirstname { get; set; }
        public string FieldFixedVersion { get; set; }
        public string FieldGeneratePassword { get; set; }
        public string FieldGroupBy { get; set; }
        public string FieldHideMail { get; set; }
        public string FieldHomepage { get; set; }
        public string FieldHost { get; set; }
        public string FieldHours { get; set; }
        public string FieldIdentifier { get; set; }
        public string FieldIdentityUrl { get; set; }
        public string FieldInheritMembers { get; set; }
        public string FieldIsClosed { get; set; }
        public string FieldIsDefault { get; set; }
        public string FieldIsFilter { get; set; }
        public string FieldIsForAll { get; set; }
        public string FieldIsInRoadmap { get; set; }
        public string FieldIsPrivate { get; set; }
        public string FieldIsPublic { get; set; }
        public string FieldIsRequired { get; set; }
        public string FieldIssue { get; set; }
        public string FieldIssueTo { get; set; }
        public string FieldIssuesVisibility { get; set; }
        public string FieldLanguage { get; set; }
        public string FieldLastLoginOn { get; set; }
        public string FieldLastname { get; set; }
        public string FieldLogin { get; set; }
        public string FieldMail { get; set; }
        public string FieldMailNotification { get; set; }
        public string FieldMaxLength { get; set; }
        public string FieldMemberOfGroup { get; set; }
        public string FieldMinLength { get; set; }
        public string FieldMultiple { get; set; }
        public string FieldMustChangePasswd { get; set; }
        public string FieldName { get; set; }
        public string FieldNewPassword { get; set; }
        public string FieldNotes { get; set; }
        public string FieldOnthefly { get; set; }
        public string FieldParent { get; set; }
        public string FieldParentIssue { get; set; }
        public string FieldParentTitle { get; set; }
        public string FieldPassword { get; set; }
        public string FieldPasswordConfirmation { get; set; }
        public string FieldPathToRepository { get; set; }
        public string FieldPort { get; set; }
        public string FieldPossibleValues { get; set; }
        public string FieldPrincipal { get; set; }
        public string FieldPriority { get; set; }
        public string FieldPrivateNotes { get; set; }
        public string FieldProject { get; set; }
        public string FieldRedirectExistingLinks { get; set; }
        public string FieldRegexp { get; set; }
        public string FieldRepositoryIsDefault { get; set; }
        public string FieldRole { get; set; }
        public string FieldRootDirectory { get; set; }
        public string FieldScmPathEncoding { get; set; }
        public string FieldSearchable { get; set; }
        public string FieldSharing { get; set; }
        public string FieldSpentOn { get; set; }
        public string FieldStartDate { get; set; }
        public string FieldStartPage { get; set; }
        public string FieldStatus { get; set; }
        public string FieldSubject { get; set; }
        public string FieldSubproject { get; set; }
        public string FieldSummary { get; set; }
        public string FieldText { get; set; }
        public string FieldTimeEntries { get; set; }
        public string FieldTimeZone { get; set; }
        public string FieldTimeout { get; set; }
        public string FieldTitle { get; set; }
        public string FieldTracker { get; set; }
        public string FieldType { get; set; }
        public string FieldUpdatedOn { get; set; }
        public string FieldUrl { get; set; }
        public string FieldUser { get; set; }
        public string FieldUsersVisibility { get; set; }
        public string FieldValue { get; set; }
        public string FieldVersion { get; set; }
        public string FieldVisible { get; set; }
        public string FieldWarnOnLeavingUnsaved { get; set; }
        public string FieldWatcher { get; set; }
        public string GeneralCsvDecimalSeparator { get; set; }
        public string GeneralCsvEncoding { get; set; }
        public string GeneralCsvSeparator { get; set; }
        public string GeneralPdfFontname { get; set; }
        public string GeneralPdfMonospacedFontname { get; set; }
        public string GeneralFirstDayOfWeek { get; set; }
        public string GeneralLangName { get; set; }
        public string GeneralTextNo { get; set; }
        public string GeneralTextYes { get; set; }
        public string DeGeneralTextNo { get; set; }
        public string DeGeneralTextYes { get; set; }
        public string LabelActivity { get; set; }
        public string LabelAddAnotherFile { get; set; }
        public string LabelAddNote { get; set; }
        public string LabelAddProjects { get; set; }
        public string LabelAdded { get; set; }
        public string LabelAddedTimeBy { get; set; }
        public string LabelAdditionalWorkflowTransitionsForAssignee { get; set; }
        public string LabelAdditionalWorkflowTransitionsForAuthor { get; set; }
        public string LabelAdministration { get; set; }
        public string LabelAge { get; set; }
        public string LabelAgo { get; set; }
        public string LabelAll { get; set; }
        public string LabelAllTime { get; set; }
        public string LabelAllWords { get; set; }
        public string LabelAndItsSubprojects { get; set; }
        public string LabelAny { get; set; }
        public string LabelAnyIssuesInProject { get; set; }
        public string LabelAnyIssuesNotInProject { get; set; }
        public string LabelApiAccessKey { get; set; }
        public string LabelApiAccessKeyCreatedOn { get; set; }
        public string LabelAppliedStatus { get; set; }
        public string LabelAscending { get; set; }
        public string LabelAsk { get; set; }
        public string LabelAssignedToMeIssues { get; set; }
        public string LabelAssociatedRevisions { get; set; }
        public string LabelAttachment { get; set; }
        public string LabelAttachmentDelete { get; set; }
        public string LabelAttachmentNew { get; set; }
        public string LabelAttachmentPlural { get; set; }
        public string LabelAttribute { get; set; }
        public string LabelAttributeOfAssignedTo { get; set; }
        public string LabelAttributeOfAuthor { get; set; }
        public string LabelAttributeOfFixedVersion { get; set; }
        public string LabelAttributeOfIssue { get; set; }
        public string LabelAttributeOfProject { get; set; }
        public string LabelAttributeOfUser { get; set; }
        public string LabelAttributePlural { get; set; }
        public string LabelAuthSource { get; set; }
        public string LabelAuthSourceNew { get; set; }
        public string LabelAuthSourcePlural { get; set; }
        public string LabelAuthentication { get; set; }
        public string LabelBetween { get; set; }
        public string LabelBlockedBy { get; set; }
        public string LabelBlocks { get; set; }
        public string LabelBoard { get; set; }
        public string LabelBoardLocked { get; set; }
        public string LabelBoardNew { get; set; }
        public string LabelBoardPlural { get; set; }
        public string LabelBoardSticky { get; set; }
        public string LabelBoolean { get; set; }
        public string LabelBranch { get; set; }
        public string LabelBrowse { get; set; }
        public string LabelBulkEditSelectedIssues { get; set; }
        public string LabelBulkEditSelectedTimeEntries { get; set; }
        public string LabelCalendar { get; set; }
        public string LabelChangePlural { get; set; }
        public string LabelChangeProperties { get; set; }
        public string LabelChangeStatus { get; set; }
        public string LabelChangeViewAll { get; set; }
        public string LabelChangesDetails { get; set; }
        public string LabelChangesetPlural { get; set; }
        public string LabelCheckboxes { get; set; }
        public string LabelCheckForUpdates { get; set; }
        public string LabelChildRevision { get; set; }
        public string LabelChronologicalOrder { get; set; }
        public string LabelCloseVersions { get; set; }
        public string LabelClosedIssues { get; set; }
        public string LabelClosedIssuesPlural { get; set; }
        public string LabelComment { get; set; }
        public string LabelCommentAdd { get; set; }
        public string LabelCommentAdded { get; set; }
        public string LabelCommentDelete { get; set; }
        public string LabelCommentPlural { get; set; }
        public string LabelCommitsPerAuthor { get; set; }
        public string LabelCommitsPerMonth { get; set; }
        public string LabelCompletedVersions { get; set; }
        public string LabelConfirmation { get; set; }
        public string LabelContains { get; set; }
        public string LabelCopied { get; set; }
        public string LabelCopiedFrom { get; set; }
        public string LabelCopiedTo { get; set; }
        public string LabelCopyAttachments { get; set; }
        public string LabelCopySameAsTarget { get; set; }
        public string LabelCopySource { get; set; }
        public string LabelCopySubtasks { get; set; }
        public string LabelCopyTarget { get; set; }
        public string LabelCopyWorkflowFrom { get; set; }
        public string LabelCrossProjectDescendants { get; set; }
        public string LabelCrossProjectHierarchy { get; set; }
        public string LabelCrossProjectSystem { get; set; }
        public string LabelCrossProjectTree { get; set; }
        public string LabelCurrentStatus { get; set; }
        public string LabelCurrentVersion { get; set; }
        public string LabelCustomField { get; set; }
        public string LabelCustomFieldNew { get; set; }
        public string LabelCustomFieldPlural { get; set; }
        public string LabelCustomFieldSelectType { get; set; }
        public string LabelDate { get; set; }
        public string LabelDateFrom { get; set; }
        public string LabelDateFromTo { get; set; }
        public string LabelDateRange { get; set; }
        public string LabelDateTo { get; set; }
        public string LabelDayPlural { get; set; }
        public string LabelDefault { get; set; }
        public string LabelDefaultColumns { get; set; }
        public string LabelDeleted { get; set; }
        public string LabelDescending { get; set; }
        public string LabelDetails { get; set; }
        public string LabelDiff { get; set; }
        public string LabelDiffInline { get; set; }
        public string LabelDiffSideBySide { get; set; }
        public string LabelDisabled { get; set; }
        public string LabelDisplay { get; set; }
        public string LabelDisplayPerPage { get; set; }
        public string LabelDisplayUsedStatusesOnly { get; set; }
        public string LabelDocument { get; set; }
        public string LabelDocumentAdded { get; set; }
        public string LabelDocumentNew { get; set; }
        public string LabelDocumentPlural { get; set; }
        public string LabelDownloadsAbbr { get; set; }
        public string LabelDropDownList { get; set; }
        public string LabelDuplicatedBy { get; set; }
        public string LabelDuplicates { get; set; }
        public string LabelEditAttachments { get; set; }
        public string LabelEnumerationNew { get; set; }
        public string LabelEnumerations { get; set; }
        public string LabelEnvironment { get; set; }
        public string LabelEquals { get; set; }
        public string LabelExample { get; set; }
        public string LabelExportOptions { get; set; }
        public string LabelExportTo { get; set; }
        public string LabelFHour { get; set; }
        public string LabelFHourPlural { get; set; }
        public string LabelFeedPlural { get; set; }
        public string LabelFeedsAccessKey { get; set; }
        public string LabelFeedsAccessKeyCreatedOn { get; set; }
        public string LabelFieldsPermissions { get; set; }
        public string LabelFileAdded { get; set; }
        public string LabelFilePlural { get; set; }
        public string LabelFilterAdd { get; set; }
        public string LabelFilterPlural { get; set; }
        public string LabelFloat { get; set; }
        public string LabelFollows { get; set; }
        public string LabelGantt { get; set; }
        public string LabelGanttProgressLine { get; set; }
        public string LabelGeneral { get; set; }
        public string LabelGenerateKey { get; set; }
        public string LabelGitReportLastCommit { get; set; }
        public string LabelGreaterOrEqual { get; set; }
        public string LabelGroup { get; set; }
        public string LabelGroupAnonymous { get; set; }
        public string LabelGroupNew { get; set; }
        public string LabelGroupNonMember { get; set; }
        public string LabelGroupPlural { get; set; }
        public string LabelHelp { get; set; }
        public string LabelHidden { get; set; }
        public string LabelHistory { get; set; }
        public string LabelHome { get; set; }
        public string LabelIn { get; set; }
        public string LabelInLessThan { get; set; }
        public string LabelInMoreThan { get; set; }
        public string LabelInTheNextDays { get; set; }
        public string LabelInThePastDays { get; set; }
        public string LabelIncomingEmails { get; set; }
        public string LabelIndexByDate { get; set; }
        public string LabelIndexByTitle { get; set; }
        public string LabelInformation { get; set; }
        public string LabelInformationPlural { get; set; }
        public string LabelInteger { get; set; }
        public string LabelInternal { get; set; }
        public string LabelIssue { get; set; }
        public string LabelIssueAdded { get; set; }
        public string LabelIssueAssignedToUpdated { get; set; }
        public string LabelIssueCategory { get; set; }
        public string LabelIssueCategoryNew { get; set; }
        public string LabelIssueCategoryPlural { get; set; }
        public string LabelIssueNew { get; set; }
        public string LabelIssueNoteAdded { get; set; }
        public string LabelIssuePlural { get; set; }
        public string LabelIssuePriorityUpdated { get; set; }
        public string LabelIssueStatus { get; set; }
        public string LabelIssueStatusNew { get; set; }
        public string LabelIssueStatusPlural { get; set; }
        public string LabelIssueStatusUpdated { get; set; }
        public string LabelIssueTracking { get; set; }
        public string LabelIssueUpdated { get; set; }
        public string LabelIssueViewAll { get; set; }
        public string LabelIssueWatchers { get; set; }
        public string LabelIssuesBy { get; set; }
        public string LabelIssuesVisibilityAll { get; set; }
        public string LabelIssuesVisibilityOwn { get; set; }
        public string LabelIssuesVisibilityPublic { get; set; }
        public string LabelItemPosition { get; set; }
        public string LabelJumpToAProject { get; set; }
        public string LabelLanguageBased { get; set; }
        public string LabelLastChanges { get; set; }
        public string LabelLastLogin { get; set; }
        public string LabelLastMonth { get; set; }
        public string LabelLastNDays { get; set; }
        public string LabelLastNWeeks { get; set; }
        public string LabelLastWeek { get; set; }
        public string LabelLatestCompatibleVersion { get; set; }
        public string LabelLatestRevision { get; set; }
        public string LabelLatestRevisionPlural { get; set; }
        public string LabelLdapAuthentication { get; set; }
        public string LabelLessOrEqual { get; set; }
        public string LabelLessThanAgo { get; set; }
        public string LabelLink { get; set; }
        public string LabelLinkCopiedIssue { get; set; }
        public string LabelLinkValuesTo { get; set; }
        public string LabelList { get; set; }
        public string LabelLoading { get; set; }
        public string LabelLoggedAs { get; set; }
        public string LabelLogin { get; set; }
        public string LabelLoginWithOpenIdOption { get; set; }
        public string LabelLogout { get; set; }
        public string LabelOnly { get; set; }
        public string LabelMaxSize { get; set; }
        public string LabelMe { get; set; }
        public string LabelMember { get; set; }
        public string LabelMemberNew { get; set; }
        public string LabelMemberPlural { get; set; }
        public string LabelMessageLast { get; set; }
        public string LabelMessageNew { get; set; }
        public string LabelMessagePlural { get; set; }
        public string LabelMessagePosted { get; set; }
        public string LabelMinMaxLength { get; set; }
        public string LabelMissingApiAccessKey { get; set; }
        public string LabelMissingFeedsAccessKey { get; set; }
        public string LabelModified { get; set; }
        public string LabelModulePlural { get; set; }
        public string LabelMonth { get; set; }
        public string LabelMonthsFrom { get; set; }
        public string LabelMore { get; set; }
        public string LabelMoreThanAgo { get; set; }
        public string LabelMyAccount { get; set; }
        public string LabelMyPage { get; set; }
        public string LabelMyPageBlock { get; set; }
        public string LabelMyProjects { get; set; }
        public string LabelMyQueries { get; set; }
        public string LabelNew { get; set; }
        public string LabelNewStatusesAllowed { get; set; }
        public string LabelNews { get; set; }
        public string LabelNewsAdded { get; set; }
        public string LabelNewsCommentAdded { get; set; }
        public string LabelNewsLatest { get; set; }
        public string LabelNewsNew { get; set; }
        public string LabelNewsPlural { get; set; }
        public string LabelNewsViewAll { get; set; }
        public string LabelNext { get; set; }
        public string LabelNoChangeOption { get; set; }
        public string LabelNoData { get; set; }
        public string LabelNoIssuesInProject { get; set; }
        public string LabelNobody { get; set; }
        public string LabelNone { get; set; }
        public string LabelNotContains { get; set; }
        public string LabelNotEquals { get; set; }
        public string LabelOpenIssues { get; set; }
        public string LabelOpenIssuesPlural { get; set; }
        public string LabelOptionalDescription { get; set; }
        public string LabelOptions { get; set; }
        public string LabelOverallActivity { get; set; }
        public string LabelOverallSpentTime { get; set; }
        public string LabelOverview { get; set; }
        public string LabelParentRevision { get; set; }
        public string LabelPasswordLost { get; set; }
        public string LabelPasswordRequired { get; set; }
        public string LabelPermissions { get; set; }
        public string LabelPermissionsReport { get; set; }
        public string LabelPersonalizePage { get; set; }
        public string LabelPlanning { get; set; }
        public string LabelPleaseLogin { get; set; }
        public string LabelPlugins { get; set; }
        public string LabelPrecedes { get; set; }
        public string LabelPreferences { get; set; }
        public string LabelPreview { get; set; }
        public string LabelPrevious { get; set; }
        public string LabelPrincipalSearch { get; set; }
        public string LabelProfile { get; set; }
        public string LabelProject { get; set; }
        public string LabelProjectAll { get; set; }
        public string LabelProjectCopyNotifications { get; set; }
        public string LabelProjectLatest { get; set; }
        public string LabelProjectNew { get; set; }
        public string LabelProjectPlural { get; set; }
        public string LabelPublicProjects { get; set; }
        public string LabelQuery { get; set; }
        public string LabelQueryNew { get; set; }
        public string LabelQueryPlural { get; set; }
        public string LabelRadioButtons { get; set; }
        public string LabelRead { get; set; }
        public string LabelReadonly { get; set; }
        public string LabelRegister { get; set; }
        public string LabelRegisteredOn { get; set; }
        public string LabelRegistrationActivationByEmail { get; set; }
        public string LabelRegistrationAutomaticActivation { get; set; }
        public string LabelRegistrationManualActivation { get; set; }
        public string LabelRelatedIssues { get; set; }
        public string LabelRelatesTo { get; set; }
        public string LabelRelationDelete { get; set; }
        public string LabelRelationNew { get; set; }
        public string LabelRenamed { get; set; }
        public string LabelReplyPlural { get; set; }
        public string LabelReport { get; set; }
        public string LabelReportPlural { get; set; }
        public string LabelReportedIssues { get; set; }
        public string LabelRepository { get; set; }
        public string LabelRepositoryNew { get; set; }
        public string LabelRepositoryPlural { get; set; }
        public string LabelRequired { get; set; }
        public string LabelResultPlural { get; set; }
        public string LabelReverseChronologicalOrder { get; set; }
        public string LabelRevision { get; set; }
        public string LabelRevisionId { get; set; }
        public string LabelRevisionPlural { get; set; }
        public string LabelRoadmap { get; set; }
        public string LabelRoadmapDueIn { get; set; }
        public string LabelRoadmapNoIssues { get; set; }
        public string LabelRoadmapOverdue { get; set; }
        public string LabelRole { get; set; }
        public string LabelRoleAndPermissions { get; set; }
        public string LabelRoleAnonymous { get; set; }
        public string LabelRoleNew { get; set; }
        public string LabelRoleNonMember { get; set; }
        public string LabelRolePlural { get; set; }
        public string LabelScm { get; set; }
        public string LabelSearch { get; set; }
        public string LabelSearchForWatchers { get; set; }
        public string LabelSearchTitlesOnly { get; set; }
        public string LabelSendInformation { get; set; }
        public string LabelSendTestEmail { get; set; }
        public string LabelSessionExpiration { get; set; }
        public string LabelSettings { get; set; }
        public string LabelShowClosedProjects { get; set; }
        public string LabelShowCompletedVersions { get; set; }
        public string LabelSort { get; set; }
        public string LabelSortBy { get; set; }
        public string LabelSortHigher { get; set; }
        public string LabelSortHighest { get; set; }
        public string LabelSortLower { get; set; }
        public string LabelSortLowest { get; set; }
        public string LabelSpentTime { get; set; }
        public string LabelStatistics { get; set; }
        public string LabelStatusTransitions { get; set; }
        public string LabelStayLoggedIn { get; set; }
        public string LabelString { get; set; }
        public string LabelSubprojectNew { get; set; }
        public string LabelSubprojectPlural { get; set; }
        public string LabelSubtaskPlural { get; set; }
        public string LabelTag { get; set; }
        public string LabelText { get; set; }
        public string LabelTheme { get; set; }
        public string LabelThisMonth { get; set; }
        public string LabelThisWeek { get; set; }
        public string LabelThisYear { get; set; }
        public string LabelTimeEntryPlural { get; set; }
        public string LabelTimeTracking { get; set; }
        public string LabelToday { get; set; }
        public string LabelTopicPlural { get; set; }
        public string LabelTotal { get; set; }
        public string LabelTotalTime { get; set; }
        public string LabelTracker { get; set; }
        public string LabelTrackerNew { get; set; }
        public string LabelTrackerPlural { get; set; }
        public string LabelUnknownPlugin { get; set; }
        public string LabelUpdateIssueDoneRatios { get; set; }
        public string LabelUpdatedTime { get; set; }
        public string LabelUpdatedTimeBy { get; set; }
        public string LabelUsedBy { get; set; }
        public string LabelUser { get; set; }
        public string LabelUserActivity { get; set; }
        public string LabelUserAnonymous { get; set; }
        public string LabelUserMailNoSelfNotified { get; set; }
        public string LabelUserMailOptionAll { get; set; }
        public string LabelUserMailOptionNone { get; set; }
        public string LabelUserMailOptionOnlyAssigned { get; set; }
        public string LabelUserMailOptionOnlyMyEvents { get; set; }
        public string LabelUserMailOptionOnlyOwner { get; set; }
        public string LabelUserMailOptionSelected { get; set; }
        public string LabelUserNew { get; set; }
        public string LabelUserPlural { get; set; }
        public string LabelUserSearch { get; set; }
        public string LabelUsersVisibilityAll { get; set; }
        public string LabelUsersVisibilityMembersOfVisibleProjects { get; set; }
        public string LabelVersion { get; set; }
        public string LabelVersionNew { get; set; }
        public string LabelVersionPlural { get; set; }
        public string LabelVersionSharingDescendants { get; set; }
        public string LabelVersionSharingHierarchy { get; set; }
        public string LabelVersionSharingNone { get; set; }
        public string LabelVersionSharingSystem { get; set; }
        public string LabelVersionSharingTree { get; set; }
        public string LabelViewAllRevisions { get; set; }
        public string LabelViewDiff { get; set; }
        public string LabelViewRevisions { get; set; }
        public string LabelVisibilityPrivate { get; set; }
        public string LabelVisibilityPublic { get; set; }
        public string LabelVisibilityRoles { get; set; }
        public string LabelWatchedIssues { get; set; }
        public string LabelWeek { get; set; }
        public string LabelWiki { get; set; }
        public string LabelWikiContentAdded { get; set; }
        public string LabelWikiContentUpdated { get; set; }
        public string LabelWikiEdit { get; set; }
        public string LabelWikiEditPlural { get; set; }
        public string LabelWikiPage { get; set; }
        public string LabelWikiPagePlural { get; set; }
        public string LabelWorkflow { get; set; }




        public LabelX LabelXClosedIssuesAbbr { get; set; }
        public LabelX LabelXComments { get; set; }
        public LabelX LabelXIssues { get; set; }
        public LabelX LabelXOpenIssuesAbbr { get; set; }
        public LabelX LabelXProjects { get; set; }

        public string LabelYear { get; set; }
        public string LabelYesterday { get; set; }
        public string MailBodyAccountActivationRequest { get; set; }
        public string MailBodyAccountInformation { get; set; }
        public string MailBodyAccountInformationExternal { get; set; }
        public string MailBodyLostPassword { get; set; }
        public string MailBodyRegister { get; set; }
        public string MailBodyReminder { get; set; }
        public string MailBodyWikiContentAdded { get; set; }
        public string MailBodyWikiContentUpdated { get; set; }
        public string MailSubjectAccountActivationRequest { get; set; }
        public string MailSubjectLostPassword { get; set; }
        public string MailSubjectRegister { get; set; }
        public string MailSubjectReminder { get; set; }
        public string MailSubjectWikiContentAdded { get; set; }
        public string MailSubjectWikiContentUpdated { get; set; }
        public string NoticeAccountActivated { get; set; }
        public string NoticeAccountDeleted { get; set; }
        public string NoticeAccountInvalidCreditentials { get; set; }
        public string NoticeAccountLostEmailSent { get; set; }
        public string NoticeAccountLocked { get; set; }
        public string NoticeAccountNotActivatedYet { get; set; }
        public string NoticeAccountPasswordUpdated { get; set; }
        public string NoticeAccountPending { get; set; }
        public string NoticeAccountRegisterDone { get; set; }
        public string NoticeAccountUnknownEmail { get; set; }
        public string NoticeAccountUpdated { get; set; }
        public string NoticeAccountWrongPassword { get; set; }
        public string NoticeApiAccessKeyReseted { get; set; }
        public string NoticeCanTChangePassword { get; set; }
        public string NoticeDefaultDataLoaded { get; set; }
        public string NoticeEmailError { get; set; }
        public string NoticeEmailSent { get; set; }
        public string NoticeFailedToSaveIssues { get; set; }
        public string NoticeFailedToSaveMembers { get; set; }
        public string NoticeFailedToSaveTimeEntries { get; set; }
        public string NoticeFeedsAccessKeyReseted { get; set; }
        public string NoticeFileNotFound { get; set; }
        public string NoticeGanttChartTruncated { get; set; }
        public string NoticeIssueDoneRatiosUpdated { get; set; }
        public string NoticeIssueSuccessfulCreate { get; set; }
        public string NoticeIssueUpdateConflict { get; set; }
        public string NoticeLockingConflict { get; set; }
        public string NoticeNewPasswordMustBeDifferent { get; set; }
        public string NoticeNoIssueSelected { get; set; }
        public string NoticeNotAuthorized { get; set; }
        public string NoticeNotAuthorizedArchivedProject { get; set; }
        public string NoticeSuccessfulConnection { get; set; }
        public string NoticeSuccessfulCreate { get; set; }
        public string NoticeSuccessfulDelete { get; set; }
        public string NoticeSuccessfulUpdate { get; set; }
        public string NoticeUnableDeleteTimeEntry { get; set; }
        public string NoticeUnableDeleteVersion { get; set; }
        public string NoticeUserSuccessfulCreate { get; set; }
        public string PermissionAddIssueNotes { get; set; }
        public string PermissionAddIssueWatchers { get; set; }
        public string PermissionAddIssues { get; set; }
        public string PermissionAddMessages { get; set; }
        public string PermissionAddProject { get; set; }
        public string PermissionAddSubprojects { get; set; }
        public string PermissionAddDocuments { get; set; }
        public string PermissionBrowseRepository { get; set; }
        public string PermissionCloseProject { get; set; }
        public string PermissionCommentNews { get; set; }
        public string PermissionCommitAccess { get; set; }
        public string PermissionDeleteIssueWatchers { get; set; }
        public string PermissionDeleteIssues { get; set; }
        public string PermissionDeleteMessages { get; set; }
        public string PermissionDeleteOwnMessages { get; set; }
        public string PermissionDeleteWikiPages { get; set; }
        public string PermissionDeleteWikiPagesAttachments { get; set; }
        public string PermissionDeleteDocuments { get; set; }
        public string PermissionEditIssueNotes { get; set; }
        public string PermissionEditIssues { get; set; }
        public string PermissionEditMessages { get; set; }
        public string PermissionEditOwnIssueNotes { get; set; }
        public string PermissionEditOwnMessages { get; set; }
        public string PermissionEditOwnTimeEntries { get; set; }
        public string PermissionEditProject { get; set; }
        public string PermissionEditTimeEntries { get; set; }
        public string PermissionEditWikiPages { get; set; }
        public string PermissionEditDocuments { get; set; }
        public string PermissionExportWikiPages { get; set; }
        public string PermissionLogTime { get; set; }
        public string PermissionManageBoards { get; set; }
        public string PermissionManageCategories { get; set; }
        public string PermissionManageFiles { get; set; }
        public string PermissionManageIssueRelations { get; set; }
        public string PermissionManageMembers { get; set; }
        public string PermissionManageNews { get; set; }
        public string PermissionManageProjectActivities { get; set; }
        public string PermissionManagePublicQueries { get; set; }
        public string PermissionManageRelatedIssues { get; set; }
        public string PermissionManageRepository { get; set; }
        public string PermissionManageSubtasks { get; set; }
        public string PermissionManageVersions { get; set; }
        public string PermissionManageWiki { get; set; }
        public string PermissionMoveIssues { get; set; }
        public string PermissionProtectWikiPages { get; set; }
        public string PermissionRenameWikiPages { get; set; }
        public string PermissionSaveQueries { get; set; }
        public string PermissionSelectProjectModules { get; set; }
        public string PermissionSetIssuesPrivate { get; set; }
        public string PermissionSetNotesPrivate { get; set; }
        public string PermissionSetOwnIssuesPrivate { get; set; }
        public string PermissionViewCalendar { get; set; }
        public string PermissionViewChangesets { get; set; }
        public string PermissionViewDocuments { get; set; }
        public string PermissionViewFiles { get; set; }
        public string PermissionViewGantt { get; set; }
        public string PermissionViewIssueWatchers { get; set; }
        public string PermissionViewIssues { get; set; }
        public string PermissionViewMessages { get; set; }
        public string PermissionViewPrivateNotes { get; set; }
        public string PermissionViewTimeEntries { get; set; }
        public string PermissionViewWikiEdits { get; set; }
        public string PermissionViewWikiPages { get; set; }
        public string ProjectModuleBoards { get; set; }
        public string ProjectModuleCalendar { get; set; }
        public string ProjectModuleDocuments { get; set; }
        public string ProjectModuleFiles { get; set; }
        public string ProjectModuleGantt { get; set; }
        public string ProjectModuleIssueTracking { get; set; }
        public string ProjectModuleNews { get; set; }
        public string ProjectModuleRepository { get; set; }
        public string ProjectModuleTimeTracking { get; set; }
        public string ProjectModuleWiki { get; set; }
        public string ProjectStatusActive { get; set; }
        public string ProjectStatusArchived { get; set; }
        public string ProjectStatusClosed { get; set; }
        public string SettingActivityDaysDefault { get; set; }
        public string SettingAppSubtitle { get; set; }
        public string SettingAppTitle { get; set; }
        public string SettingAttachmentMaxSize { get; set; }
        public string SettingAutofetchChangesets { get; set; }
        public string SettingAutologin { get; set; }
        public string SettingBccRecipients { get; set; }
        public string SettingCacheFormattedText { get; set; }
        public string SettingCommitCrossProjectRef { get; set; }
        public string SettingCommitFixKeywords { get; set; }
        public string SettingCommitLogtimeActivityId { get; set; }
        public string SettingCommitLogtimeEnabled { get; set; }
        public string SettingCommitRefKeywords { get; set; }
        public string SettingCrossProjectIssueRelations { get; set; }
        public string SettingCrossProjectSubtasks { get; set; }
        public string SettingDateFormat { get; set; }
        public string SettingDefaultIssueStartDateToCreationDate { get; set; }
        public string SettingDefaultLanguage { get; set; }
        public string SettingDefaultNotificationOption { get; set; }
        public string SettingDefaultProjectsModules { get; set; }
        public string SettingDefaultProjectsPublic { get; set; }
        public string SettingDefaultProjectsTrackerIds { get; set; }
        public string SettingDiffMaxLinesDisplayed { get; set; }
        public string SettingDisplaySubprojectsIssues { get; set; }
        public string SettingEmailsFooter { get; set; }
        public string SettingEmailsHeader { get; set; }
        public string SettingEnabledScm { get; set; }
        public string SettingFeedsLimit { get; set; }
        public string SettingFileMaxSizeDisplayed { get; set; }
        public string SettingForceDefaultLanguageForAnonymous { get; set; }
        public string SettingForceDefaultLanguageForLoggedin { get; set; }
        public string SettingGanttItemsLimit { get; set; }
        public string SettingGravatarDefault { get; set; }
        public string SettingGravatarEnabled { get; set; }
        public string SettingHostName { get; set; }
        public string SettingIssueDoneRatio { get; set; }
        public string SettingIssueDoneRatioIssueField { get; set; }
        public string SettingIssueDoneRatioIssueStatus { get; set; }
        public string SettingIssueGroupAssignment { get; set; }
        public string SettingIssueListDefaultColumns { get; set; }
        public string SettingIssuesExportLimit { get; set; }
        public string SettingJsonpEnabled { get; set; }
        public string SettingLinkCopiedIssue { get; set; }
        public string SettingLoginRequired { get; set; }
        public string SettingMailFrom { get; set; }
        public string SettingMailHandlerApiEnabled { get; set; }
        public string SettingMailHandlerApiKey { get; set; }
        public string SettingMailHandlerBodyDelimiters { get; set; }
        public string SettingMailHandlerExcludedFilenames { get; set; }
        public string SettingNewProjectUserRoleId { get; set; }
        public string SettingNonWorkingWeekDays { get; set; }
        public string SettingOpenid { get; set; }
        public string SettingPasswordMinLength { get; set; }
        public string SettingPasswordMaxAge { get; set; }
        public string SettingPerPageOptions { get; set; }
        public string SettingPlainTextMail { get; set; }
        public string SettingProtocol { get; set; }
        public string SettingRepositoriesEncodings { get; set; }
        public string SettingRepositoryLogDisplayLimit { get; set; }
        public string SettingRestApiEnabled { get; set; }
        public string SettingSelfRegistration { get; set; }
        public string SettingSequentialProjectIdentifiers { get; set; }
        public string SettingSessionLifetime { get; set; }
        public string SettingSessionTimeout { get; set; }
        public string SettingStartOfWeek { get; set; }
        public string SettingSysApiEnabled { get; set; }
        public string SettingTextFormatting { get; set; }
        public string SettingThumbnailsEnabled { get; set; }
        public string SettingThumbnailsSize { get; set; }
        public string SettingTimeFormat { get; set; }
        public string SettingUnsubscribe { get; set; }
        public string SettingUserFormat { get; set; }
        public string SettingWelcomeText { get; set; }
        public string SettingWikiCompression { get; set; }
        public string StatusActive { get; set; }
        public string StatusLocked { get; set; }
        public string StatusRegistered { get; set; }
        public string TextAccountDestroyConfirmation { get; set; }
        public string TextAreYouSure { get; set; }
        public string TextAssignTimeEntriesToProject { get; set; }
        public string TextCaractersMaximum { get; set; }
        public string TextCaractersMinimum { get; set; }
        public string TextCommaSeparated { get; set; }
        public string TextConvertAvailable { get; set; }
        public string TextCustomFieldPossibleValuesInfo { get; set; }
        public string TextDefaultAdministratorAccountChanged { get; set; }
        public string TextDestroyTimeEntries { get; set; }
        public string TextDestroyTimeEntriesQuestion { get; set; }
        public string TextDiffTruncated { get; set; }
        public string TextEmailDeliveryNotConfigured { get; set; }
        public string TextEnumerationCategoryReassignTo { get; set; }
        public string TextEnumerationDestroyQuestion { get; set; }
        public string TextFileRepositoryWritable { get; set; }
        public string TextGitRepositoryNote { get; set; }
        public string TextIssueAdded { get; set; }
        public string TextIssueCategoryDestroyAssignments { get; set; }
        public string TextIssueCategoryDestroyQuestion { get; set; }
        public string TextIssueCategoryReassignTo { get; set; }
        public string TextIssueConflictResolutionAddNotes { get; set; }
        public string TextIssueConflictResolutionCancel { get; set; }
        public string TextIssueConflictResolutionOverwrite { get; set; }
        public string TextIssueUpdated { get; set; }
        public string TextIssuesDestroyConfirmation { get; set; }
        public string TextIssuesDestroyDescendantsConfirmation { get; set; }
        public string TextIssuesRefInCommitMessages { get; set; }
        public string TextJournalAdded { get; set; }
        public string TextJournalChanged { get; set; }
        public string TextJournalChangedNoDetail { get; set; }
        public string TextJournalDeleted { get; set; }
        public string TextJournalSetTo { get; set; }
        public string TextLengthBetween { get; set; }
        public string TextLineSeparated { get; set; }
        public string TextLoadDefaultConfiguration { get; set; }
        public string TextMercurialRepositoryNote { get; set; }
        public string TextMinMaxLengthInfo { get; set; }
        public string TextNoConfigurationData { get; set; }
        public string TextOwnMembershipDeleteConfirmation { get; set; }
        public string TextPluginAssetsWritable { get; set; }
        public string TextProjectClosed { get; set; }
        public string TextProjectDestroyConfirmation { get; set; }
        public string TextProjectIdentifierInfo { get; set; }
        public string TextReassignTimeEntries { get; set; }
        public string TextRegexpInfo { get; set; }
        public string TextRepositoryIdentifierInfo { get; set; }
        public string TextRepositoryUsernamesMapping { get; set; }
        public string TextRmagickAvailable { get; set; }
        public string TextScmCommand { get; set; }
        public string TextScmCommandNotAvailable { get; set; }
        public string TextScmCommandVersion { get; set; }
        public string TextScmConfig { get; set; }
        public string TextScmPathEncodingNote { get; set; }
        public string TextSelectMailNotifications { get; set; }
        public string TextSelectProjectModules { get; set; }
        public string TextSessionExpirationSettings { get; set; }
        public string TextStatusChangedByChangeset { get; set; }
        public string TextSubprojectsDestroyWarning { get; set; }
        public string TextSubversionRepositoryNote { get; set; }
        public string TextTimeEntriesDestroyConfirmation { get; set; }
        public string TextTimeLoggedByChangeset { get; set; }
        public string TextTipIssueBeginDay { get; set; }
        public string TextTipIssueBeginEndDay { get; set; }
        public string TextTipIssueEndDay { get; set; }
        public string TextTrackerNoWorkflow { get; set; }
        public string TextTurningMultipleOff { get; set; }
        public string TextUnallowedCharacters { get; set; }
        public string TextUserMailOption { get; set; }
        public string TextUserWrote { get; set; }
        public string TextWarnOnLeavingUnsaved { get; set; }
        public string TextWikiDestroyConfirmation { get; set; }
        public string TextWikiPageDestroyChildren { get; set; }
        public string TextWikiPageDestroyQuestion { get; set; }
        public string TextWikiPageNullifyChildren { get; set; }
        public string TextWikiPageReassignChildren { get; set; }
        public string TextWorkflowEdit { get; set; }
        public string TextZoomIn { get; set; }
        public string TextZoomOut { get; set; }
        public string VersionStatusClosed { get; set; }
        public string VersionStatusLocked { get; set; }
        public string VersionStatusOpen { get; set; }
        public string WarningAttachmentsNotSaved { get; set; }
        public string LabelSearchAttachmentsYes { get; set; }
        public string LabelSearchAttachmentsNo { get; set; }
        public string LabelSearchAttachmentsOnly { get; set; }
        public string LabelSearchOpenIssuesOnly { get; set; }
        public string FieldAddress { get; set; }
        public string SettingMaxAdditionalEmails { get; set; }
        public string LabelEmailAddressPlural { get; set; }
        public string LabelEmailAddressAdd { get; set; }
        public string LabelEnableNotifications { get; set; }
        public string LabelDisableNotifications { get; set; }
        public string SettingSearchResultsPerPage { get; set; }
        public string LabelBlankValue { get; set; }
        public string PermissionCopyIssues { get; set; }
        public string ErrorPasswordExpired { get; set; }
        public string FieldTimeEntriesVisibility { get; set; }
        public string LabelParentTaskAttributes { get; set; }
        public string LabelParentTaskAttributesDerived { get; set; }
        public string LabelParentTaskAttributesIndependent { get; set; }
        public string LabelTimeEntriesVisibilityAll { get; set; }
        public string LabelTimeEntriesVisibilityOwn { get; set; }
        public string LabelMemberManagement { get; set; }
        public string LabelMemberManagementAllRoles { get; set; }
        public string LabelMemberManagementSelectedRolesOnly { get; set; }
        public string LabelTotalSpentTime { get; set; }
        public string NoticeImportFinished { get; set; }
        public string NoticeImportFinishedWithErrors { get; set; }
        public string ErrorInvalidFileEncoding { get; set; }
        public string ErrorInvalidCsvFileOrSettings { get; set; }
        public string ErrorCanNotReadImportFile { get; set; }
        public string PermissionImportIssues { get; set; }
        public string LabelImportIssues { get; set; }
        public string LabelSelectFileToImport { get; set; }
        public string LabelFieldsSeparator { get; set; }
        public string LabelFieldsWrapper { get; set; }
        public string LabelEncoding { get; set; }
        public string LabelCommaChar { get; set; }
        public string LabelSemiColonChar { get; set; }
        public string LabelQuoteChar { get; set; }
        public string LabelDoubleQuoteChar { get; set; }
        public string LabelFieldsMapping { get; set; }
        public string LabelFileContentPreview { get; set; }
        public string LabelCreateMissingValues { get; set; }
        public string ButtonImport { get; set; }
        public string FieldTotalEstimatedHours { get; set; }
        public string LabelApi { get; set; }
        public string LabelTotalPlural { get; set; }
        public string LabelAssignedIssues { get; set; }
        public string LabelFieldFormatEnumeration { get; set; }
        public string LabelFHourShort { get; set; }
        public string FieldDefaultVersion { get; set; }
        public string ErrorAttachmentExtensionNotAllowed { get; set; }
        public string SettingAttachmentExtensionsAllowed { get; set; }
        public string SettingAttachmentExtensionsDenied { get; set; }
        public string LabelAnyOpenIssues { get; set; }
        public string LabelNoOpenIssues { get; set; }
        public string LabelDefaultValuesForNewUsers { get; set; }
        
    }

    public class Activerecord
    {
        public Errors Errors { get; set; }
    }

    public class Errors
    {
        public Template Template { get; set; }
        public Dictionary<string, string> Messages { get; set; }
    }

    public class Template
    {
        public Header Header { get; set; }
        public string Body { get; set; }
    }

    public class Header
    {
        public string One { get; set; }
        public string Other { get; set; }
    }

    public class Date
    {
        public Formats Formats { get; set; }
        public List<string> DayNames { get; set; }
        public List<string> AbbrDayNames { get; set; }
        public List<string> MonthNames { get; set; }
        public List<string> AbbrMonthNames { get; set; }
        public List<string> Order { get; set; }
    }

    public class Formats
    {
        public string Default { get; set; }
        public string Short { get; set; }
        public string Long { get; set; }
        public string Time { get; set; }
    }

    public class Datetime
    {
        public DistanceInWords DistanceInWords { get; set; }
    }

    public class DistanceInWords
    {
        public string HalfAMinute { get; set; }
        public Header LessThanXSeconds { get; set; }
        public Header XSeconds { get; set; }
        public Header LessThanXMinutes { get; set; }
        public Header XMinutes { get; set; }
        public Header AboutXHours { get; set; }
        public Header XHours { get; set; }
        public Header XDays { get; set; }
        public Header AboutXMonths { get; set; }
        public Header XMonths { get; set; }
        public Header AboutXYears { get; set; }
        public Header OverXYears { get; set; }
        public Header AlmostXYears { get; set; }
    }

    public class LabelX
    {
        public string Zero { get; set; }
        public string One { get; set; }
        public string Other { get; set; }
    }

    public class Number
    {
        public NumberFormat Format { get; set; }
        public Currency Currency { get; set; }
        public Percentage Percentage { get; set; }
        public Percentage Precision { get; set; }
        public Human Human { get; set; }
    }

    public class Currency
    {
        public CurrencyFormat Format { get; set; }
    }

    public class CurrencyFormat
    {
        public string Unit { get; set; }
        public string Format { get; set; }
        public string Delimiter { get; set; }
    }

    public class NumberFormat
    {
        public string Separator { get; set; }
        public string Delimiter { get; set; }
        public string Precision { get; set; }
    }

    public class Human
    {
        public HumanFormat Format { get; set; }
        public StorageUnits StorageUnits { get; set; }
    }

    public class HumanFormat
    {
        public string Delimiter { get; set; }
        public string Precision { get; set; }
    }

    public class StorageUnits
    {
        public string Format { get; set; }
        public Units Units { get; set; }
    }

    public class Units
    {
        public Header Byte { get; set; }
        public string Kb { get; set; }
        public string Mb { get; set; }
        public string Gb { get; set; }
        public string Tb { get; set; }
    }

    public class Percentage
    {
        public PercentageFormat Format { get; set; }
    }

    public class PercentageFormat
    {
        public string Delimiter { get; set; }
    }

    public class Support
    {
        public Array Array { get; set; }
    }

    public class Array
    {
        public string SentenceConnector { get; set; }
        public string SkipLastComma { get; set; }
    }

    public class Time
    {
        public Formats Formats { get; set; }
        public string Am { get; set; }
        public string Pm { get; set; }
    }

}
