
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[V_DELDATA_PrimaryKeyColumns]'))
DROP VIEW [dbo].[V_DELDATA_PrimaryKeyColumns]
GO





CREATE VIEW [dbo].[V_DELDATA_PrimaryKeyColumns]  
AS 
SELECT 
	 ccu.TABLE_SCHEMA
	,ccu.TABLE_NAME
	,ccu.COLUMN_NAME
	,ccu.CONSTRAINT_NAME
	,ic.ORDINAL_POSITION 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc

LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu 
	ON tc.CONSTRAINT_NAME = ccu.Constraint_name 
	
LEFT JOIN INFORMATION_SCHEMA.COLUMNS AS ic
	ON ic.TABLE_SCHEMA = ccu.TABLE_SCHEMA
	AND ic.TABLE_NAME = ccu.TABLE_NAME
	AND ic.COLUMN_NAME = ccu.COLUMN_NAME 
	
WHERE tc.CONSTRAINT_TYPE = 'PRIMARY KEY'


--TABLE_CATALOG	TABLE_SCHEMA	TABLE_NAME
--COR_Basic	dbo	T_ZO_AP_Kontakte_AP_Ref_Kostenstelle

--ORDER BY TABLE_NAME, COLUMN_NAME 


GO

