SELECT 
	 tc.TABLE_SCHEMA 
	,tc.TABLE_NAME 
	,tc.CONSTRAINT_NAME 
	,tc.CONSTRAINT_TYPE
	,ccu.COLUMN_NAME 
	,'ALTER TABLE ' + QUOTENAME(tc.TABLE_SCHEMA) + '.' + QUOTENAME(tc.TABLE_NAME) + ' 
	ADD  CONSTRAINT ' + QUOTENAME(tc.CONSTRAINT_NAME) + ' UNIQUE ( ' + QUOTENAME(ccu.COLUMN_NAME) + ')' 
	
-- IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[T_Benutzergruppen]') AND name = N'uc_BG_Name')
-- ALTER TABLE [dbo].[T_Benutzergruppen] ADD  CONSTRAINT [uc_BG_Name] UNIQUE ( [Name] )
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc 

LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS ccu 
	ON ccu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME 
	AND ccu.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA 
	AND ccu.TABLE_NAME = tc.TABLE_NAME 
	AND ccu.TABLE_SCHEMA = tc.TABLE_SCHEMA 

WHERE (1=1) 
-- AND CONSTRAINT_TYPE NOT IN ('PRIMARY KEY', 'FOREIGN KEY', 'CHECK', 'UNIQUE') 
AND CONSTRAINT_TYPE = 'UNIQUE'  





-- SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
-- SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE 

-- SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES 
-- SELECT * FROM INFORMATION_SCHEMA.COLUMN_PRIVILEGES 