
-- LOKAL

SELECT 
	 (SELECT COUNT(*) AS ViewCount FROM INFORMATION_SCHEMA.VIEWS  ) AS ViewCount 
	,(SELECT COUNT(*) AS ProcedureCount FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' ) AS ProcedureCount
	,(SELECT COUNT(*) AS TableFunctionCount FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION' AND DATA_TYPE = 'TABLE') AS TableFunctionCount
	,(SELECT COUNT(*) AS ScalarFunctionCount FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION' AND ISNULL(DATA_TYPE, '') <> 'TABLE') AS ScalarFunctionCount 
	,'Local' AS machine 

UNION 

SELECT 
	 (SELECT COUNT(*) AS ViewCount FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.VIEWS  ) AS ViewCount 
	,(SELECT COUNT(*) AS ProcedureCount FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' ) AS ProcedureCount 
	,(SELECT COUNT(*) AS TableFunctionCount FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION' AND DATA_TYPE = 'TABLE') AS TableFunctionCount 
	,(SELECT COUNT(*) AS ScalarFunctionCount FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION' AND ISNULL(DATA_TYPE, '') <> 'TABLE') AS ScalarFunctionCount 
	,'REMOTEDB' AS machine 







SELECT 
	 REMOTEDBViews.TABLE_SCHEMA AS REMOTEDBSchema 
	,REMOTEDBViews.TABLE_NAME AS REMOTEDBView 
	,LocalViews.TABLE_SCHEMA AS LocalSchema 
	,LocalViews.TABLE_NAME AS LocalView 
FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.VIEWS AS REMOTEDBViews
FULL JOIN INFORMATION_SCHEMA.VIEWS AS LocalViews
	ON LocalViews.TABLE_SCHEMA = REMOTEDBViews.TABLE_SCHEMA
	AND LocalViews.TABLE_NAME = REMOTEDBViews.TABLE_NAME

WHERE REMOTEDBViews.TABLE_NAME LIKE 'V[_]%' OR REMOTEDBViews.TABLE_NAME IS NULL 







SELECT 
	 REMOTEDBRoutines.ROUTINE_SCHEMA AS REMOTEDBSchema 
	,REMOTEDBRoutines.ROUTINE_NAME AS REMOTEDBRoutine 
	,REMOTEDBRoutines.ROUTINE_TYPE AS REMOTEDBRoutineType 
	,LocalRoutines.ROUTINE_SCHEMA AS LocalSchema 
	,LocalRoutines.ROUTINE_NAME AS LocalRoutine 
	,LocalRoutines.ROUTINE_TYPE AS LocalRoutineType 
FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.ROUTINES AS REMOTEDBRoutines
FULL JOIN INFORMATION_SCHEMA.ROUTINES AS LocalRoutines
	ON LocalRoutines.ROUTINE_SCHEMA = REMOTEDBRoutines.ROUTINE_SCHEMA
	AND LocalRoutines.ROUTINE_NAME = REMOTEDBRoutines.ROUTINE_NAME
WHERE (REMOTEDBRoutines.ROUTINE_TYPE = 'PROCEDURE' AND REMOTEDBRoutines.ROUTINE_NAME LIKE 'sp[_]%'  AND REMOTEDBRoutines.ROUTINE_NAME NOT IN ('sp_creatediagram', 'sp_renamediagram', 'sp_alterdiagram', 'sp_helpdiagramdefinition', 'sp_upgraddiagrams', 'sp_dropdiagram', 'sp_helpdiagrams') ) 
OR ( LocalRoutines.ROUTINE_TYPE = 'PROCEDURE' AND LocalRoutines.ROUTINE_NAME LIKE 'sp[_]%' AND LocalRoutines.ROUTINE_NAME NOT IN ('sp_creatediagram', 'sp_renamediagram', 'sp_alterdiagram', 'sp_helpdiagramdefinition', 'sp_upgraddiagrams', 'sp_dropdiagram', 'sp_helpdiagrams') ) 





SELECT 
	 REMOTEDBRoutines.ROUTINE_SCHEMA AS REMOTEDBSchema 
	,REMOTEDBRoutines.ROUTINE_NAME AS REMOTEDBRoutine 
	,REMOTEDBRoutines.ROUTINE_TYPE AS REMOTEDBRoutineType 
	,LocalRoutines.ROUTINE_SCHEMA AS LocalSchema 
	,LocalRoutines.ROUTINE_NAME AS LocalRoutine 
	,LocalRoutines.ROUTINE_TYPE AS LocalRoutineType 
FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.ROUTINES  AS REMOTEDBRoutines
FULL JOIN INFORMATION_SCHEMA.ROUTINES  AS LocalRoutines
	ON LocalRoutines.ROUTINE_SCHEMA = REMOTEDBRoutines.ROUTINE_SCHEMA
	AND LocalRoutines.ROUTINE_NAME = REMOTEDBRoutines.ROUTINE_NAME
WHERE ( REMOTEDBRoutines.ROUTINE_TYPE = 'FUNCTION' AND REMOTEDBRoutines.DATA_TYPE <> 'TABLE' AND REMOTEDBRoutines.ROUTINE_NAME NOT IN ('fn_diagramobjects') )
OR ( LocalRoutines.ROUTINE_TYPE = 'FUNCTION' AND LocalRoutines.DATA_TYPE <> 'TABLE' AND LocalRoutines.ROUTINE_NAME NOT IN ('fn_diagramobjects'))




SELECT 
	 REMOTEDBRoutines.ROUTINE_SCHEMA AS REMOTEDBSchema 
	,REMOTEDBRoutines.ROUTINE_NAME AS REMOTEDBRoutine 
	,REMOTEDBRoutines.ROUTINE_TYPE AS REMOTEDBRoutineType 
	,LocalRoutines.ROUTINE_SCHEMA AS LocalSchema 
	,LocalRoutines.ROUTINE_NAME AS LocalRoutine 
	,LocalRoutines.ROUTINE_TYPE AS LocalRoutineType 
FROM REMOTEDB.DB_TO_COMPARE.INFORMATION_SCHEMA.ROUTINES  AS REMOTEDBRoutines
FULL JOIN INFORMATION_SCHEMA.ROUTINES  AS LocalRoutines
	ON LocalRoutines.ROUTINE_SCHEMA = REMOTEDBRoutines.ROUTINE_SCHEMA
	AND LocalRoutines.ROUTINE_NAME = REMOTEDBRoutines.ROUTINE_NAME
WHERE ( REMOTEDBRoutines.ROUTINE_TYPE = 'FUNCTION' AND REMOTEDBRoutines.DATA_TYPE = 'TABLE' )
OR ( LocalRoutines.ROUTINE_TYPE = 'FUNCTION' AND LocalRoutines.DATA_TYPE = 'TABLE' )

