
SELECT 
	 tc.TABLE_SCHEMA
	,tc.TABLE_NAME 
	,tc.CONSTRAINT_SCHEMA
	,tc.CONSTRAINT_NAME 
	,tc.CONSTRAINT_TYPE 
	 
	,N'IF NOT EXISTS(
	SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc 
	WHERE tc.CONSTRAINT_TYPE = ''UNIQUE'' 
	AND CONSTRAINT_SCHEMA = ''' + tc.CONSTRAINT_SCHEMA + N''' 
	AND CONSTRAINT_NAME = ''' + tc.CONSTRAINT_NAME + N''' 
	AND TABLE_SCHEMA = ''' + tc.TABLE_SCHEMA + N''' 
	AND TABLE_NAME = ''' + tc.TABLE_NAME + N''' 
) '
	+  N'ALTER TABLE ' + QUOTENAME(tc.TABLE_SCHEMA) + N'.' + QUOTENAME(tc.TABLE_NAME) + N' ' 
	+ N'ADD CONSTRAINT ' + QUOTENAME(tc.CONSTRAINT_NAME) + N' UNIQUE (' + tUniqueColumns.column_names + N');  ' 
	AS SqlCreateUniqueConstraint 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc 

OUTER APPLY 
	(
		SELECT 
			STUFF
			(
				(
					SELECT 
						 N', ' + QUOTENAME(cc.COLUMN_NAME) AS [text()]
					FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS cc 
					WHERE tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME 
					AND tc.CONSTRAINT_SCHEMA= cc.CONSTRAINT_SCHEMA 

					FOR XML PATH(''), TYPE
				).value('.', 'nvarchar(MAX)')
				,1,2,''
			) AS column_names 
	) AS tUniqueColumns

WHERE tc.CONSTRAINT_TYPE = 'UNIQUE' 

ORDER BY 
	 tc.CONSTRAINT_SCHEMA 
	,tc.CONSTRAINT_NAME 
	 